# Generated by Django 2.1.2 on 2018-12-08 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pyano2', '0003_auto_20181208_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='declined',
            new_name='done',
        ),
        migrations.AddField(
            model_name='invitation',
            name='created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not decided'), (1, 'Accepted'), (2, 'Declined')], default=0),
        ),
    ]
