# Generated by Django 2.1.2 on 2018-12-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyano2', '0005_auto_20181208_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
