# Generated by Django 2.1.2 on 2018-12-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyano2', '0008_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='point',
            field=models.FloatField(default=1.0, help_text='The number of credits user will be paid for a job done.'),
        ),
    ]
