# Generated by Django 2.1.2 on 2018-12-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyano2', '0009_auto_20181209_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not decided'), (1, 'Accepted'), (2, 'Declined'), (3, 'Expired')], default=0),
        ),
    ]
