# Generated by Django 2.1.2 on 2018-12-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyano2', '0011_auto_20181212_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaticjob',
            name='ready',
            field=models.BooleanField(default=False, help_text='Whether if the job is ready.'),
        ),
    ]
