# Generated by Django 2.1.2 on 2018-12-13 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20181208_1426'),
        ('pyano2', '0014_remove_vaticjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why', models.IntegerField(choices=[(1, 'Downloaded'), (2, 'Irrelevant'), (3, 'Bad quality'), (4, 'Duplicated or not novel')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='survey.Video')),
            ],
        ),
    ]
