# Generated by Django 2.1.2 on 2018-12-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyano2', '0015_bannedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='message',
            field=models.TextField(auto_created=True, blank=True, default='', max_length=4096),
        ),
    ]
