# Generated by Django 2.1.2 on 2018-12-20 22:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pyano2', '0016_invitation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreebaseTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('googleId', models.CharField(default='/m/01hrs3', max_length=32)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pyanoTopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freebases', to='pyano2.Topic')),
            ],
        ),
    ]
