# Generated by Django 2.0.7 on 2018-08-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResultPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_idx', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='searchresult',
            name='pref',
            field=models.TextField(blank=True),
        ),
    ]
